# Generated by Django 3.2.3 on 2021-06-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productcategory_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
